# Generated by Django 3.1.4 on 2020-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20201215_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='entity',
            new_name='network',
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(),
        ),
    ]
