# Generated by Django 3.1.4 on 2020-12-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20201215_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'verbose_name': 'entity', 'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['entity_id', 'networkType', 'id'], 'verbose_name': 'social network', 'verbose_name_plural': 'social networks'},
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ['network_id', 'date'], 'verbose_name': 'social post', 'verbose_name_plural': 'social posts'},
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='isDefault',
            new_name='is_default',
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='directory.entity'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='directory.socialnetwork'),
        ),
    ]
