# Generated by Django 3.1.4 on 2020-12-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20201215_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['entity_id', 'network_type', 'id'], 'verbose_name': 'social network', 'verbose_name_plural': 'social networks'},
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='iconUrl',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='networkType',
            new_name='network_type',
        ),
        migrations.RenameField(
            model_name='socialpost',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
