# Generated by Django 3.1.4 on 2020-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20201216_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='account_name',
            field=models.CharField(blank=True, help_text='For Twitter/Facebook/Instagram, give the @AccountName', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='feed_url',
            field=models.URLField(blank=True, help_text='for blogs, give the RSS/Atom feed url'),
        ),
    ]
