# Generated by Django 3.1.4 on 2020-12-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20201216_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialpost',
            options={'ordering': ['network_id', '-date'], 'verbose_name': 'social post', 'verbose_name_plural': 'social posts'},
        ),
        migrations.AddField(
            model_name='entity',
            name='web',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
